// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http

import (
	"github.com/email2vimalraj/graphss/pkg/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer(configFilePath string) (*Server, error) {
	cfg, err := config.NewCfg(configFilePath)
	if err != nil {
		return nil, err
	}
	server, err := New(cfg)
	if err != nil {
		return nil, err
	}
	return server, nil
}

// wire.go:

var providerSet = wire.NewSet(config.NewCfg, New)
